name: Prueba de Tokens

on:
  push:

jobs:
  comparar_tokens:
    runs-on: self-hosted
    steps:
      - name: Comparar DEV_TOKEN de GitHub con LOCAL_DEV_TOKEN local
        env:
          SECRET_DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if ($env:SECRET_DEV_TOKEN -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "✅ ÉXITO: Los tokens coinciden perfectamente."
            exit 0
          } else {
            Write-Host "❌ ERROR: Los tokens no coinciden."
            exit 1
          } 